

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'CREATE_USER', N'Create User', N'1', N'Create User', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'EDIT_USER', N'Edit User', N'1', N'Edit User', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'DELETE_USER', N'Delete User', N'1', N'Delete User', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));



INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'CREATE_PERMISSION', N'Create Permission', N'1', N'Create Permission', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'EDIT_PERMISSION', N'Edit Permission', N'1', N'Edit Permission', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'DELETE_PERMISSION', N'Delete Permission', N'1', N'Delete Permission', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

	
	
INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'CREATE_ROLE', N'Create Role', N'1', N'Create Role', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'EDIT_ROLE', N'Edit Role', N'1', N'Edit Role', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'DELETE_ROLE', N'Delete Role', N'1', N'Delete Role', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));


INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'CREATE_MENU', N'Create Menu', N'1', N'Create Menu', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'EDIT_MENU', N'Edit Menu', N'1', N'Edit Menu', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

INSERT INTO [dbo].[SECURITY_PERMISSION] ([CREATE_TIME], [CREATE_USER], [LAST_UPDATE_TIME], [LAST_UPDATE_USER], [ALIAS], [DESCRIPTION], [ENABLED], [NAME], [SYSTEM_ID]) 
	VALUES (N'2017-01-24 16:47:08.560', N'admin', N'2017-01-24 16:47:08.560', N'admin', N'DELETE_MENU', N'Delete Menu', N'1', N'Delete Menu', (select SECURITY_SYSTEM_ID from SECURITY_SYSTEM where ALIAS = 'maxim'));

	

	